### ISSUE TITLE
transitionTo is deprecated, use transitionToRoute

### ISSUE THREAD

**Issue by goodtimeaj** [embercasts/authentication-part-2#2]
From Ember debug: "transitionTo is deprecated. Please use transitionToRoute."

This is for `LoginController` only, not `AuthenticatedRoute`

**Comment by machty** [comment]
Where are you seeing this? We use `transitionToRoute`: https://github.com/embercasts/authentication-part-2/blob/master/public/js/app.js#L98

We use `transitionTo` within the Route class, but for Controllers you need to use `transitionToRoute`, but I think we're doing it correctly, no?

**Comment by goodtimeaj** [comment]
Oh, the video changes screens right before you change to `transitionToRoute`. I see the code is correct, though.

![screen shot 2013-08-29 at 11 37 46 am](https://f.cloud.github.com/assets/447556/1052268/4d2d09a2-10da-11e3-9d3c-afe0221b5d18.png)

**Comment by machty** [comment]
Ah, good catch, I'll try to change if I have time.
